### ISSUE TITLE
Display source/documentation for individual model files

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/earm#5]
Because these files don't contain functions as members, they don't get a viewcode link to the source. We need some way to link to the source.

Two options:
- Hack viewcode.py to work with modules, not just functions
- Write an add-on extension that monkeypatches viewcode to do the right thing

**Comment by jmuhlich** [comment]
Implemented in cff7494698db01aacab364b905c09f35a5c09045. I went with option 1 (copy and modify viewcode.py).
